### ISSUE TITLE
The method getApplicationDocumentsDirectory() isn't defined

### ISSUE THREAD

**Issue by mrcartier** [DeveloperLibs/flutter_database#1]
In database_hepler.dart was this renamed or supposed to be somewhere else? See screenshot...

![screen shot 2018-11-05 at 11 22 14 am](https://user-images.githubusercontent.com/6580221/48011460-c615f980-e0ed-11e8-9e4a-3f6905bfb85d.png)

**Comment by mrcartier** [comment]
Had to add to pubspec.yaml, builds fine now without issue

    environment:
       sdk: ">=2.0.0-dev.68.0 <3.0.0"

**Comment by MightyCoderX** [comment]
It still doesnt work for me

**Comment by danilosilvadev** [comment]
i have the same issue

**Comment by yasarthewise** [comment]
same issue here

**Comment by Henrydykee** [comment]
dosen't work for me either

**Comment by Henrydykee** [comment]
import 'package:path_provider/path_provider.dart';
 add this line to your import
 make sure you have path_provider: ^1.6.24 in your pubspec.ymal file
